export enum ErrorTypes {
    UNKNOWN = 'UNKNOWN',
    NO_PERMISSIONS = 'NO_PERMISSIONS',
    NOT_FOUND = 'NOT_FOUND',
    DELETION_ERROR = 'DELETION_ERROR',
    BAD_DATA = 'BAD_DATA',
    ALREADY_EXISTS = 'ALREADY_EXISTS',
    LIMIT_EXCEEDED = 'LIMIT_EXCEEDED',
    INTERNAL = 'INTERNAL',
}
