import StoreProvider from 'Providers/StoreProvider';
import type { Metadata } from 'next';
import 'react-circular-progressbar/dist/styles.css';
import 'simplebar-react/dist/simplebar.min.css';
import { store } from 'store';
import { api } from 'store/api';
import 'styles/global.scss';
import Hydrator from './hydrator';

export const dynamic = 'force-dynamic';

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

async function RootLayout({ children }: { children: React.ReactNode }) {
    const { data } = await store.dispatch(api.endpoints.test.initiate());

    console.log(123, data);

    return (
        <html lang="en">
            <body>
                <StoreProvider data={{ test: data, api: store.getState().api }}>{children}</StoreProvider>
            </body>
        </html>
    );
}

export default RootLayout;
