import StoreProvider from 'Providers/StoreProvider';
import type { Metadata } from 'next';
import { store } from 'store';
import { api } from 'store/api';
import { config } from '@fortawesome/fontawesome-svg-core';
import 'react-circular-progressbar/dist/styles.css';
import 'simplebar-react/dist/simplebar.min.css';
import 'styles/global.scss';
import '@fortawesome/fontawesome-svg-core/styles.css';
import MainLayout from 'layouts/MainLayout';

config.autoAddCss = false;

export const dynamic = 'force-dynamic';

export const metadata: Metadata = {
    title: {
        template: '%s | Wars.Cash',
        default: 'Wars.Cash',
    },
    description: 'Generated by create next app',
};

async function RootLayout({ children }: { children: React.ReactNode }) {
    // const { data } = await store.dispatch(api.endpoints.test.initiate());

    return (
        <html lang="ru">
            <body>
                <StoreProvider data={{ api: store.getState().api }}>
                    <MainLayout>{children}</MainLayout>
                </StoreProvider>
            </body>
        </html>
    );
}

export default RootLayout;
