name: Deployment
on:
    workflow_dispatch:
    push:
        branches:
            - master
        paths-ignore:
            - '.github/workflows/*'
jobs:
    lint:
        runs-on: ubuntu-22.04
        steps:
            - name: Get repository code
              uses: actions/checkout@v3
            - name: Cache deps
              uses: actions/cache@v3
              with:
                  path: ~/.npm
                  key: node-modules-${{ hashFiles('**/package-lock.json') }}
            - name: Install dependencies
              run: npm ci
            - name: Lint
              run: npm run lint
    deploy:
        runs-on: ubuntu-22.04
        needs: lint
        steps:
            - name: Get repository code
              uses: actions/checkout@v3
            - name: Cache deps
              uses: actions/cache@v3
              with:
                  path: ~/.npm
                  key: node-modules-${{ hashFiles('**/package-lock.json') }}
            - name: Install dependencies
              run: npm ci
            - name: Build
              run: npm run build
            - name: Setup SSH
              run: |
                  mkdir -p ~/ssh/
                  echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/ssh/id_rsa
                  echo "${{ secrets.SSH_USER }}" > ~/ssh/id_rsa.pub
                  chmod 600 ~/ssh/id_rsa
                  chmod 600 ~/ssh/id_rsa.pub
                  ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/ssh/known_hosts
            - name: Deploy build on server
              run: |
                  rsync -vrm .next/* ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:~/apps/wars-cash/dist
                  ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "pm2 restart all"
