name: Deployment
on:
    workflow_dispatch:
    push:
        branches:
            - master
        paths-ignore:
            - '.github/workflows/*'
jobs:
    lint:
        runs-on: ubuntu-22.04
        steps:
            - name: Get repository code
              uses: actions/checkout@v3
            - name: Cache deps
              uses: actions/cache@v3
              with:
                  path: ~/.npm
                  key: node-modules-${{ hashFiles('**/package-lock.json') }}
            - name: Install dependencies
              run: npm ci
            - name: Lint
              run: npm run lint
    deploy:
        runs-on: ubuntu-22.04
        needs: lint
        steps:
            - name: Get repository code
              uses: actions/checkout@v3
            - name: Cache deps
              uses: actions/cache@v3
              with:
                  path: ~/.npm
                  key: node-modules-${{ hashFiles('**/package-lock.json') }}
            - name: Install dependencies
              run: npm ci
            - name: Build
              run: npm run build
            - name: Setup SSH
              uses: shimataro/ssh-key-action@v2
              with:
                  key: ${{ secrets.SSH_PRIVATE_KEY }}
                  known_hosts: ${{ secrets.KNOWN_HOSTS }}
            - name: Deploy build on server
              run: |
                  rsync -vrm ./* ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:~/apps/wars-cash
                  ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "npm ci"
                  ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "pm2 restart wars-cash"
