name: Deployment
on:
    workflow_dispatch:
    push:
        branches:
            - master
        paths-ignore:
            - '.github/workflows/*'
jobs:
    deploy:
        runs-on: ubuntu-22.04
        steps:
            - name: Setup SSH
              uses: shimataro/ssh-key-action@v2
              with:
                  key: ${{ secrets.SSH_PRIVATE_KEY }}
                  known_hosts: ${{ secrets.KNOWN_HOSTS }}
            - name: Deploy build on server
              run: |
                  ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "cd ~/apps/wars-cash && rm -rf .next && git pull origin master && npm ci && npm run build && pm2 restart wars-cash"
