name: Production Deployment
on:
    workflow_dispatch:
    push:
        branches:
            - master
        paths-ignore:
            - '.github/workflows/*'
jobs:
    deploy:
        runs-on: ubuntu-22.04
        steps:
            - name: Get repository code
              uses: actions/checkout@v3
            - name: Cache deps
              uses: actions/cache@v3
              with:
                  path: ~/.npm
                  key: node-modules-${{ hashFiles('**/package-lock.json') }}
            - name: Install dependencies
              run: npm ci
            - name: Build
              run: npm run build
            - name: Create env file
              run: echo "$ENV_PROD" > .env.production
              env:
                  ENV_PROD: ${{ secrets.ENV_PROD }}
            - name: Setup SSH
              uses: shimataro/ssh-key-action@v2
              with:
                  key: ${{ secrets.SSH_PRIVATE_KEY }}
                  known_hosts: ${{ secrets.KNOWN_HOSTS }}
            - name: Deploy on server
              run: |
                  rsync -avz ./.env.development ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:~/apps/wars-cash
                  ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "cd ~/apps/wars-cash && git pull origin master && npm ci && rm -rf .next && npm run build && pm2 restart wars-cash --update-env"
